pipeline:
  name: "pipe30"
  identifier: "pipe30"
  projectIdentifier: "imranTest"
  orgIdentifier: "default"
  storeType: "REMOTE"
  remoteType: "create"
  tags: {}
  stages:
  - stage:
      name: "a1"
      identifier: "a1"
      description: ""
      type: "Approval"
      spec:
        execution:
          steps:
          - step:
              name: "ap1"
              identifier: "ap1"
              type: "HarnessApproval"
              timeout: "1d"
              spec:
                approvalMessage: "Please review the following information\nand approve\
                  \ the pipeline progression"
                includePipelineExecutionHistory: true
                approvers:
                  minimumCount: 1
                  disallowPipelineExecutor: false
                  userGroups: "<+input>"
                approverInputs: []
      tags: {}
  description: ""
