pipeline:
  name: "pipe28"
  identifier: "pipe28"
  projectIdentifier: "imranTest"
  orgIdentifier: "default"
  storeType: "REMOTE"
  remoteType: "create"
  tags: {}
  stages:
  - stage:
      name: "ap1"
      identifier: "ap1"
      description: ""
      type: "Approval"
      spec:
        execution:
          steps:
          - step:
              name: "g1"
              identifier: "g1"
              type: "HarnessApproval"
              timeout: "1d"
              spec:
                approvalMessage: "Please review the following information\nand approve\
                  \ the pipeline progression"
                includePipelineExecutionHistory: true
                approvers:
                  minimumCount: 1
                  disallowPipelineExecutor: false
                  userGroups: "<+input>"
                approverInputs: []
      tags: {}
  - stage:
      name: "sq"
      identifier: "sq"
      description: ""
      type: "Custom"
      spec:
        execution:
          steps:
          - step:
              type: "ShellScript"
              name: "sh1"
              identifier: "sh1"
              spec:
                shell: "Bash"
                onDelegate: true
                source:
                  type: "Inline"
                  spec:
                    script: "echo \"done\"\nexit 0"
                environmentVariables: []
                outputVariables: []
                executionTarget: {}
              timeout: "10m"
      tags: {}
  description: ""
