pipeline:
    name: updatingExisitngStuff
    identifier: updatingExisitngStuff
    projectIdentifier: GitXTest
    orgIdentifier: GitXorg
    tags: {}
    stages:
        - stage:
              name: S1
              identifier: S1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: <+input>
                      serviceDefinition:
                          spec:
                              variables: []
                          type: Kubernetes
                  infrastructure:
                      environmentRef: <+input>
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: <+input>
                              namespace: <+input>
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - step:
                                type: Verify
                                name: Verify
                                identifier: Verify
                                timeout: 2h
                                spec:
                                    type: Canary
                                    monitoredService:
                                        type: Default
                                        spec: {}
                                    spec:
                                        sensitivity: <+input>
                                        duration: <+input>
                                        deploymentTag: <+serviceConfig.artifacts.primary.tag>
                                failureStrategies:
                                    - onFailure:
                                          errors:
                                              - Verification
                                          action:
                                              type: ManualIntervention
                                              spec:
                                                  timeout: 2h
                                                  onTimeout:
                                                      action:
                                                          type: StageRollback
                                    - onFailure:
                                          errors:
                                              - Unknown
                                          action:
                                              type: ManualIntervention
                                              spec:
                                                  timeout: 2h
                                                  onTimeout:
                                                      action:
                                                          type: Ignore
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
